// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MYPROJECT2.Models;

public partial class Group
{
    [Key]
    [Column("GROUP_ID")]
    public int GroupId { get; set; }

    [Required]
    [Column("NAME")]
    [StringLength(50)]
    public string Name { get; set; }

    [Column("LEADER_ID")]
    public int? LeaderId { get; set; }

    [InverseProperty("Group")]
    public virtual ICollection<Børn> Børns { get; set; } = new List<Børn>();

    [ForeignKey("LeaderId")]
    [InverseProperty("Groups")]
    public virtual Leader Leader { get; set; }
}