// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MYPROJECT2.Models;

[Table("Leader")]
public partial class Leader
{
    [Key]
    [Column("LEADER_ID")]
    public int LeaderId { get; set; }

    [Required]
    [Column("NAME")]
    [StringLength(50)]
    public string Name { get; set; }

    [Required]
    [Column("USER_ID")]
    [StringLength(50)]
    public string UserId { get; set; }

    [Column("APPOINTED", TypeName = "datetime")]
    public DateTime Appointed { get; set; }

    [InverseProperty("Leader")]
    public virtual ICollection<Assigment> Assigments { get; set; } = new List<Assigment>();

    [InverseProperty("Leader")]
    public virtual ICollection<Group> Groups { get; set; } = new List<Group>();

    [InverseProperty("Leader")]
    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();
}