// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MYPROJECT2.Models;

[PrimaryKey("SaleId", "ChildId")]
[Table("Sale")]
public partial class Sale
{
    [Key]
    [Column("SALE_ID")]
    public int SaleId { get; set; }

    [Column("TICKET_ID")]
    public int? TicketId { get; set; }

    [Required]
    [Column("STUTUS")]
    [StringLength(50)]
    public string Stutus { get; set; }

    [Column("LEADER_ID")]
    public int? LeaderId { get; set; }

    [Key]
    [Column("CHILD_ID")]
    public int ChildId { get; set; }

    [ForeignKey("ChildId")]
    [InverseProperty("Sales")]
    public virtual Børn Child { get; set; }

    [ForeignKey("LeaderId")]
    [InverseProperty("Sales")]
    public virtual Leader Leader { get; set; }

    [ForeignKey("TicketId")]
    [InverseProperty("Sales")]
    public virtual Ticket Ticket { get; set; }
}