// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MYPROJECT2.Models;

public partial class Ticket
{
    [Key]
    [Column("TICKET_ID")]
    public int TicketId { get; set; }

    [Column("PRICE")]
    public int Price { get; set; }

    [Required]
    [Column("STUTUS")]
    [StringLength(50)]
    public string Stutus { get; set; }

    [Column("CREATED", TypeName = "datetime")]
    public DateTime Created { get; set; }

    [InverseProperty("Ticket")]
    public virtual ICollection<Assigment> Assigments { get; set; } = new List<Assigment>();

    [InverseProperty("Ticket")]
    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();
}